platform :ios, '10.0'
use_frameworks!

target 'KMKeys_Example' do
  pod 'KMKeys', :path => '../'

  target 'KMKeys_Tests' do
    inherit! :search_paths
    pod 'KMKeys', :path => '../'

    pod 'Quick'
    pod 'Nimble'
  end
end
